version: '3'
services:
  db:
    image: mysql
    restart: always
    ports:
      - "${HOST_DB}:3306"
    environment:
      MYSQL_DATABASE: 'backend_core'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""
    volumes:
      - ./.docker/db:/var/lib/mysql
  pma:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DB_HOST}
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
      - PMA_PORT=${DB_PORT}
    ports:
      - "${HOST_PMD}:80"
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravel-test-docker'
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ./:/var/www/html
